#!/usr/bin/env python3
from __future__ import annotations

import re
from pathlib import Path

TARGET_NAMES = {
    "T6_INTRODUCTION.md",
    "T6_CHAPTER_2.md",
    "T6_CHAPTER_3.md",
    "T6_CONCLUSION.md",
}

# Ordered replacements. Long/specific phrases go first so that the editorial
# layer remains deterministic and does not touch citations, numbers or model IDs.
REPLACEMENTS = [
    ("NLP-, sentiment- и aspect-based методы", "NLP-методы, анализ тональности и аспектный анализ"),
    ("open review datasets", "открытые наборы данных отзывов"),
    ("review datasets", "наборы данных отзывов"),
    ("Yandex Geo Reviews Dataset", "набор данных Yandex Geo Reviews Dataset"),
    ("implementation-agnostic", "независимый от конкретной технической реализации"),
    ("response/action/outcome", "ответ/мероприятие/подтверждённый результат"),
    ("response ≠ action ≠ outcome", "ответ ≠ мероприятие ≠ подтверждённый результат"),
    ("response vs verified resolution", "публичные ответы и подтверждённые результаты"),
    ("expert verification high-criticality случаев", "экспертную проверку случаев высокой критичности"),
    ("high-criticality screening cases", "случаев предварительного выявления высокой критичности"),
    ("high-criticality", "высокой критичности"),
    ("critical triggers", "критерии критичности"),
    ("Critical trigger", "Критерий критичности"),
    ("critical trigger", "критерий критичности"),
    ("expert verification", "экспертная проверка"),
    ("Expert verification", "Экспертная проверка"),
    ("legal/compliance review", "юридическая и комплаенс-проверка"),
    ("Legal/Compliance", "Юридическая/комплаенс-функция"),
    ("verification flag", "признак экспертной проверки"),
    ("C3/C4 verification rate", "доля проверенных C3/C4"),
    ("classification completeness", "полнота классификации"),
    ("provenance completeness", "полнота прослеживаемости источника"),
    ("traceability completeness", "полнота прослеживаемости"),
    ("data-quality exception rate", "доля исключений по качеству данных"),
    ("median time to triage", "медианное время первичной оценки"),
    ("median time to route", "медианное время маршрутизации"),
    ("verified resolution rate", "доля подтверждённых результатов"),
    ("verified resolution", "подтверждённый результат"),
    ("action coverage", "охват внутренними мероприятиями"),
    ("corrective action closure rate", "доля завершённых корректирующих мероприятий"),
    ("repeat problem rate", "доля повторяющихся проблем"),
    ("reopen rate", "доля повторно открытых случаев"),
    ("Public response rate", "Доля публичных ответов"),
    ("public response rate", "доля публичных ответов"),
    ("response rate", "доля публичных ответов"),
    ("resolved rate", "доля подтверждённых решений"),
    ("corrective actions", "корректирующие мероприятия"),
    ("corrective action", "корректирующее мероприятие"),
    ("audit trail", "журнал изменений"),
    ("source metadata", "метаданные источника"),
    ("data contract", "единая структура данных"),
    ("codebook version", "версия кодировочной схемы"),
    ("Codebook", "Кодировочная схема"),
    ("codebook", "кодировочная схема"),
    ("multi-label классификатор", "многометочный классификатор"),
    ("multi-label классификации", "многометочной классификации"),
    ("multi-label классификация", "многометочная классификация"),
    ("multi-label аспекты", "многометочные аспекты"),
    ("multi-label логике", "логике многометочной классификации"),
    ("multi-label частоты аспектов", "частоты аспектов при многометочной классификации"),
    ("multi-label", "многометочный"),
    ("screening-критичности", "предварительной критичности"),
    ("screening-уровнями", "предварительными уровнями"),
    ("screening-кейса", "случая предварительного выявления"),
    ("screening-кейсов", "случаев предварительного выявления"),
    ("screening cases", "случаев предварительного выявления"),
    ("screening", "предварительное выявление"),
    ("Rule-based распределение", "Распределение на основе правил"),
    ("rule-based скринингом", "предварительной оценкой на основе правил"),
    ("rule-based классификации", "классификации на основе правил"),
    ("rule-based/автоматическим предположением", "предположением, полученным на основе правил или автоматизированного анализа"),
    ("rule-based", "основанный на правилах"),
    ("rating-proxy", "прокси-оценке по рейтингу"),
    ("sentiment-proxy", "прокси-тональности"),
    ("sentiment analysis", "анализа тональности"),
    ("aspect-based analysis", "аспектного анализа"),
    ("traceability", "прослеживаемость"),
    ("provenance", "прослеживаемость источника"),
    ("dedup", "дедупликация"),
    ("response/action/outcome", "ответ/мероприятие/подтверждённый результат"),
    ("outcome", "подтверждённый результат"),
    ("observability gap", "ограничение наблюдаемости"),
    ("evidence triangulation", "триангуляция доказательств"),
    ("Evidence pack", "Пакет доказательных материалов"),
    ("evidence pack", "пакет доказательных материалов"),
    ("evidence repository", "хранилище доказательных материалов"),
    ("evidence plan", "план доказательной проверки"),
    ("training evidence", "материалы подтверждения обучения"),
    ("evidence policy", "политика доказательности"),
    ("эмпирическое evidence", "эмпирические данные"),
    ("эмпирическому evidence", "эмпирическим данным"),
    ("наблюдаемым evidence", "наблюдаемыми доказательными данными"),
    ("наблюдаемое evidence", "наблюдаемые доказательные данные"),
    ("между evidence и", "между доказательными данными и"),
    ("evidence P3", "данные P3"),
    ("evidence главы 2", "данным главы 2"),
    ("формировании evidence", "формировании доказательной базы"),
    ("Если evidence воспроизводимо", "Если доказательные данные воспроизводимы"),
    ("evidence воспроизводимо", "доказательные данные воспроизводимы"),
    ("evidence невозможно", "доказательные данные невозможно"),
    ("evidence второй главы", "доказательным данным второй главы"),
    ("pilot scope", "границы пилота"),
    ("scope", "границы пилота"),
    ("baseline window", "базовое окно наблюдения"),
    ("BEFORE baseline", "базовый период «до»"),
    ("AFTER measurement", "измерение «после»"),
    ("BEFORE/AFTER", "сравнение «до/после»"),
    ("dry-run", "пробный прогон"),
    ("preregistration", "предварительная фиксация методики оценки"),
    ("preregistered", "предварительно зафиксированные"),
    ("post-hoc", "последующее"),
    ("Anti-cherry-picking rule", "Правило против выборочного представления результатов"),
    ("anti-cherry-picking rule", "правило против выборочного представления результатов"),
    ("stop-risks", "риски остановки"),
    ("stop-risk", "риск остановки"),
    ("guardrails", "защитные ограничения"),
    ("privacy/security incident", "инцидент в области защиты персональных данных или информационной безопасности"),
    ("privacy rules", "правила защиты персональных данных"),
    ("privacy", "защита персональных данных"),
    ("decision gate", "контрольная точка принятия решения"),
    ("Decision gate", "Контрольная точка принятия решения"),
    ("integrity gates", "контрольные проверки целостности"),
    ("integrity", "целостность доказательной базы"),
    ("success criteria", "критерии успеха"),
    ("risk snapshots", "срезы рисков"),
    ("decision record", "итоговый протокол решения"),
    ("data-quality reports", "отчёты о качестве данных"),
    ("event log", "журнал событий"),
    ("exception/change log", "журнал исключений и изменений"),
    ("verification log", "журнал проверок"),
    ("datasets", "наборы данных"),
    ("dataset", "набор данных"),
    ("mapping источника", "сопоставление полей источника"),
    ("raw/accepted/excluded/duplicates", "исходные/принятые/исключённые/дубликаты"),
    ("rationale", "обоснование"),
    ("reopened cases", "повторно открытые случаи"),
    ("repeat problems", "повторяющиеся проблемы"),
    ("RACI mapping", "сопоставление ролей RACI"),
    ("KPI definitions", "определения KPI"),
    ("C3/C4 open", "открытые C3/C4"),
    ("source group", "группа источника"),
    ("source name", "наименование источника"),
    ("triage", "первичная оценка"),
    ("case ID", "идентификатор случая"),
    ("open", "открытые"),
]

FORBIDDEN_AFTER_R1 = (
    "implementation-agnostic",
    "provenance",
    "codebook",
    "multi-label",
    "screening",
    "expert verification",
    "critical trigger",
    "legal/compliance review",
    "verification flag",
    "response/action/outcome",
    "observability gap",
    "evidence triangulation",
    "rating-proxy",
    "sentiment-proxy",
)

# Final case-insensitive cleanup for the three terms that occur in mixed-case
# headings/table labels in T6. These replacements are lexical only and cannot
# alter numbers, citations or internal IDs.
CASE_INSENSITIVE_REPLACEMENTS = [
    (r"screening", "предварительное выявление"),
    (r"response/action/outcome", "ответ/мероприятие/подтверждённый результат"),
    (r"observability gap", "ограничение наблюдаемости"),
]


def normalize_text(text: str) -> str:
    for old, new in REPLACEMENTS:
        text = text.replace(old, new)
    for pattern, new in CASE_INSENSITIVE_REPLACEMENTS:
        text = re.sub(pattern, new, text, flags=re.IGNORECASE)
    return text


def normalize_file(src: Path, dst: Path) -> None:
    text = src.read_text(encoding="utf-8-sig")
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(normalize_text(text), encoding="utf-8")
